### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Dejvi1** [ruptz/Rup-DeathLog#2]
Hi, pleae would you be so kind and could u add also log for victims inventory ?
In the case of troll kill it would help a lot to restore victims stuff. 

If thats possible to add, it would be really lovely

**Comment by ruptz** [comment]
Will look into it

**Comment by ruptz** [comment]
Closed: Want to keep the resource standalone for people so they can use on any framework. If anyone wants to make a pull request that keeps in mind about people running servers without inventories I will review it and merge.
